version: '3.1'

services:
  freeradius_bng_api:
    build: .
    volumes:
      - /usr/share/freeradius/:/freeradius_dictionaries:ro
    ports:
      - "8083:80"
    env_file:
      - .env
  #  links:
  #    - mongo:mongo
  #mongo:
  #  image: mongo:4.4.6
  #  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: freeradius
  #    MONGO_INITDB_ROOT_PASSWORD: changemeP!z
  #  ports:
  #    - 27017:27017